### ISSUE TITLE
Create a Csv to pdf generator python code for generating the bill for the customers of our website.

### ISSUE THREAD

**Issue by Sohoxic** [SarthakSKumar/IoTforHire-Website#8]
I am Soham Sarkar, a sophomore at PES University. I would love to contribute to the bill generator needed for handling the customer's financial details for the purchase from our website. Create a Csv to pdf generator python code for generating the bill for the customers of our website.

**Comment by SarthakSKumar** [comment]
Assigned @Sohoxic

**Comment by Sohoxic** [comment]
Thank you.
